assetSelection:
  baseAsset: BTC
  exchangeList: [Binance]
  name: All
dbName: disco
enter: {bolStd: 1, granularity: 21600, name: CheapVol, periodsMA: 100, periodsVolLong: 100,
  periodsVolShort: 5, volCoef: 1.5}
exit:
  closePeriods: 5
  granularity: 7200
  maPeriods: 50
  name: ProfitRun
  stdDict: {down: 1, up: 0.5}
logging: {console: 10, file: 20}
positionSize: {name: Basic, percent: 0.05}
stratName: CheapVol_ProfitRun
